In [1]:
import pandas as pd

In [3]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
type(s1)

pandas.core.series.Series

In [16]:
s1 = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])

In [18]:
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [22]:
pd.Series({'a':'10','b':'20','c':'30'})

a    10
b    20
c    30
dtype: object

In [24]:
pd.Series({'a':10,'b':20,'c':30}, index = ['b','c','d','a'])

b    20.0
c    30.0
d     NaN
a    10.0
dtype: float64

In [32]:
l1 = [1,2,3,4,5,6,7,8,9]

In [34]:
s1 = pd.Series(l1)

In [36]:
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [38]:
s1[4]

5

In [44]:
s1[:5]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [48]:
s1[-5:]

4    5
5    6
6    7
7    8
8    9
dtype: int64

In [50]:
s1 +5

0     6
1     7
2     8
3     9
4    10
5    11
6    12
7    13
8    14
dtype: int64

In [60]:
s2 = pd.Series([10,20,30,40,50,60,70,80])

In [62]:
s1+s2

0    11.0
1    22.0
2    33.0
3    44.0
4    55.0
5    66.0
6    77.0
7    88.0
8     NaN
dtype: float64

In [64]:
s2

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
dtype: int64

In [58]:
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [66]:
s1-s2

0    -9.0
1   -18.0
2   -27.0
3   -36.0
4   -45.0
5   -54.0
6   -63.0
7   -72.0
8     NaN
dtype: float64

In [68]:
 #Data Frames

In [74]:
df1 = pd.DataFrame({"Name": ['Bob','Sam','Anne'],"Marks":[76,25,92]})

In [76]:
df1

   Name  Marks
0   Bob     76
1   Sam     25
2  Anne     92

In [78]:
type(df1)

pandas.core.frame.DataFrame

In [88]:
iris = pd.read_csv('iris.csv')

In [90]:
#iris.head(), iris.tail(), iris.shape, iris.describe()

In [92]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [94]:
iris.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [100]:
iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [104]:
iris.shape

(150, 6)

In [106]:
#iris.iloc[0:3, 0:2], iris.loc()

In [112]:
iris.iloc[5:11,2:] #here 11 is not inclusive

    SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
5            3.9            1.7           0.4  Iris-setosa
6            3.4            1.4           0.3  Iris-setosa
7            3.4            1.5           0.2  Iris-setosa
8            2.9            1.4           0.2  Iris-setosa
9            3.1            1.5           0.1  Iris-setosa
10           3.7            1.5           0.2  Iris-setosa

In [118]:
iris.loc[1:10,("SepalLengthCm","PetalLengthCm")] #here 10 is inclusive

    SepalLengthCm  PetalLengthCm
1             4.9            1.4
2             4.7            1.3
3             4.6            1.5
4             5.0            1.4
5             5.4            1.7
6             4.6            1.4
7             5.0            1.5
8             4.4            1.4
9             4.9            1.5
10            5.4            1.5

In [122]:
iris.drop('SepalLengthCm',axis=1)

      Id  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1           3.5            1.4           0.2     Iris-setosa
1      2           3.0            1.4           0.2     Iris-setosa
2      3           3.2            1.3           0.2     Iris-setosa
3      4           3.1            1.5           0.2     Iris-setosa
4      5           3.6            1.4           0.2     Iris-setosa
..   ...           ...            ...           ...             ...
145  146           3.0            5.2           2.3  Iris-virginica
146  147           2.5            5.0           1.9  Iris-virginica
147  148           3.0            5.2           2.0  Iris-virginica
148  149           3.4            5.4           2.3  Iris-virginica
149  150           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [124]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [126]:
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [128]:
i1 = iris.drop([5,6,7],axis = 0)

In [130]:
i1.head(10)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa

In [132]:
iris.min()

Id                         1
SepalLengthCm            4.3
SepalWidthCm             2.0
PetalLengthCm            1.0
PetalWidthCm             0.1
Species          Iris-setosa
dtype: object

In [134]:
iris.max()

Id                          150
SepalLengthCm               7.9
SepalWidthCm                4.4
PetalLengthCm               6.9
PetalWidthCm                2.5
Species          Iris-virginica
dtype: object

In [150]:
i1 = i1.drop("Species",axis = 1)

In [152]:
i1.mean()

Id               76.897959
SepalLengthCm     5.860544
SepalWidthCm      3.043537
PetalLengthCm     3.804082
PetalWidthCm      1.217007
dtype: float64

In [154]:
i1.median()

Id               77.0
SepalLengthCm     5.8
SepalWidthCm      3.0
PetalLengthCm     4.4
PetalWidthCm      1.3
dtype: float64

In [158]:
i1.mode()

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.0           3.0            1.5           0.2
1      2            5.1           NaN            NaN           NaN
2      3            6.3           NaN            NaN           NaN
3      4            NaN           NaN            NaN           NaN
4      5            NaN           NaN            NaN           NaN
..   ...            ...           ...            ...           ...
142  146            NaN           NaN            NaN           NaN
143  147            NaN           NaN            NaN           NaN
144  148            NaN           NaN            NaN           NaN
145  149            NaN           NaN            NaN           NaN
146  150            NaN           NaN            NaN           NaN

[147 rows x 5 columns]

In [168]:
iris[['SepalLengthCm','PetalLengthCm']].apply(half)

     SepalLengthCm  PetalLengthCm
0             2.55           0.70
1             2.45           0.70
2             2.35           0.65
3             2.30           0.75
4             2.50           0.70
..             ...            ...
145           3.35           2.60
146           3.15           2.50
147           3.25           2.60
148           3.10           2.70
149           2.95           2.55

[150 rows x 2 columns]

In [180]:
def double_make(s):
    return s*2

In [186]:
iris[['SepalWidthCm','PetalWidthCm']].apply(double_make)

     SepalWidthCm  PetalWidthCm
0             7.0           0.4
1             6.0           0.4
2             6.4           0.4
3             6.2           0.4
4             7.2           0.4
..            ...           ...
145           6.0           4.6
146           5.0           3.8
147           6.0           4.0
148           6.8           4.6
149           6.0           3.6

[150 rows x 2 columns]

In [190]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [194]:
iris['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [198]:
iris.sort_values(by='P    Cm')

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
13,14,4.3,3.0,1.1,0.1,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
...,...,...,...,...,...,...
122,123,7.7,2.8,6.7,2.0,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica